name: CI

on:
  push:
    # For code coverage reports
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      # Codecov uploads with use_oidc: true
      id-token: write
    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-go@v7
        with:
          go-version-file: go.mod
          cache-dependency-path: go.sum

      - run: make build
      - run: make test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v7
        with:
          use_oidc: true
          files: cover.profile

  nix:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v7

      - uses: unmango/actions/setup-nix@389dda3b9e44477f790e76d5474b700c1bb9b82d # v1.3.0
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - run: nix flake check --all-systems
      - run: nix build
